local lush = require('lush')
local colors = require('lush-theme.colors')

local spec = lush(function()
  return {
    -- Buffer line highlight groups
    -- BufferLineInfoDiagnosticSelected    {},
    -- BufferLineBuffer                    {},
    -- BufferLineInfoDiagnostic            {},
    -- BufferLineInfoSelected              {},
    -- BufferLineInfoVisible               {},
    -- BufferLineHintDiagnosticSelected    {},
    -- BufferLineHintDiagnosticVisible     {},
    -- BufferLineHintDiagnostic            {},
    -- BufferLineHintSelected              {},
    -- BufferLineHintVisible               {},
    -- BufferLineHint                      {},
    -- BufferLineDiagnosticSelected        {},
    -- BufferLineDiagnosticVisible         {},
    -- BufferLineNumbersVisible            {},
    -- BufferLineNumbersSelected           {},
    -- BufferLineNumbers                   {},
    -- BufferLineBufferSelected            {},
    -- BufferLineBufferVisible             {},
    -- BufferLineCloseButtonSelected       {},
    -- BufferLineDiagnostic                {},
    -- BufferLineInfo                      {},
    -- BufferLineTabClose                  {},
    -- BufferLineBackground                {},
    -- BufferLineGroupLabel                {},
    -- BufferLineGroupSeparator            {},
    -- BufferLineTruncMarker               {},
    -- BufferLineFill                      {},
    -- BufferLineTab                       {},
    -- BufferLineInfoDiagnosticVisible     {},
    -- BufferLineCloseButtonVisible        {},
    -- BufferLineError                     {},
    -- BufferLineTabSelected               {},
    -- BufferLineCloseButton               {},
    -- BufferLineSeparator                 {},
    -- BufferLineModified                  {},
    -- BufferLineModifiedVisible           {},
    -- BufferLineOffsetSeparator           {},
    -- BufferLinePickVisible               {},
    -- BufferLinePickSelected              {},
    -- BufferLineIndicatorVisible          {},
    -- BufferLineIndicatorSelected         {},
    -- BufferLineTabSeparatorSelected      {},
    -- BufferLineTabSeparator              {},
    -- BufferLineSeparatorVisible          {},
    -- BufferLineSeparatorSelected         {},
    -- BufferLineDuplicate                 {},
    -- BufferLineDuplicateVisible          {},
    -- BufferLineDuplicateSelected         {},
    -- BufferLineModifiedSelected          {},
    -- BufferLinePick                      {},
    -- BufferLineErrorDiagnosticSelected   {},
    -- BufferLineErrorDiagnosticVisible    {},
    -- BufferLineErrorDiagnostic           {},
    -- BufferLineErrorSelected             {},
    -- BufferLineErrorVisible              {},
    -- BufferLineWarningDiagnosticSelected {},
    -- BufferLineWarningDiagnosticVisible  {},
    -- BufferLineWarningDiagnostic         {},
    -- BufferLineWarningSelected           {},
    -- BufferLineWarningVisible            {},
    -- BufferLineWarning                   {},
  }
end)

return spec

-- vi:nowrap
